# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cybX6qUqQ4SNrXlyamT-62uZn6ATJrJO
"""

import pandas as pd

data = {
    'student_id': ['S1','S2','S3','S4','S5','S6'],
    'attendance_percent': [85,92,78,88,95,70],
    'assignment_score': [40,45,35,42,48,30],
    'quiz_score': [38,40,32,39,45,28],
    'lab_completed': [True,True,False,True,True,False]
}

df = pd.DataFrame(data)

df['total_score'] = df['assignment_score'] + df['quiz_score']

df['eligible'] = (
    (df['attendance_percent'] >= 80) &
    (df['total_score'] >= 75) &
    (df['lab_completed'])
)

df

df.head()

"""# Feature Engineering"""

df['average_score'] = (
    df['assignment_score'] +
    df['quiz_score']
) / 2

df['score_gap'] = (
    df['assignment_score'] -
    df['quiz_score']
)

df['score_efficiency'] = (
    df['total_score'] /
    df['attendance_percent']
)

df['lab_completed_numeric'] = (
    df['lab_completed'].astype(int)
)

df['performance_level'] = pd.cut(
    df['total_score'],
    bins=[0, 60, 80, 100],
    labels=['Low', 'Medium', 'High']
)

df.head()



"""# Data Visualization"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.bar(df['student_id'], df['total_score'])
plt.title('Total Score by Student')
plt.xlabel('Student ID')
plt.ylabel('Total Score')
plt.show()

plt.figure(figsize=(8,5))
plt.scatter(
    df['attendance_percent'],
    df['total_score']
)
plt.title('Attendance vs Total Score')
plt.xlabel('Attendance %')
plt.ylabel('Total Score')
plt.grid(True)
plt.show()

eligibility_counts = df['eligible'].value_counts()

plt.figure(figsize=(6,6))
plt.pie(
    eligibility_counts,
    labels=eligibility_counts.index,
    autopct='%1.1f%%'
)
plt.title('Eligibility Distribution')
plt.show()

plt.figure(figsize=(8,5))

plt.plot(
    df['student_id'],
    df['assignment_score'],
    marker='o',
    label='Assignment Score'
)

plt.plot(
    df['student_id'],
    df['quiz_score'],
    marker='s',
    label='Quiz Score'
)

plt.legend()
plt.title('Assignment vs Quiz Scores')
plt.xlabel('Student')
plt.ylabel('Score')
plt.show()